name: Build Qt Project with MinGW

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # 安装 Ninja 构建工具
    - name: Install Ninja
      run: choco install ninja

    # 安装 MinGW
    - name: Install MinGW
      run: choco install mingw

    # 设置环境变量（让后续命令能找到 MinGW）
    - name: Add MinGW to PATH
      shell: powershell
      run: echo "C:\\tools\\mingw64\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append


    # 安装 Qt（MinGW版，整包）
    - name: Install Qt (MinGW)
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
        target: desktop
        arch: win64_mingw
        # 不写 modules，安装完整包

    # CMake 配置，使用 Ninja 和 MinGW
    - name: Configure with CMake and Ninja
      run: cmake -S . -B build -G Ninja

    # 构建
    - name: Build with Ninja
      run: cmake --build build --parallel

    # 上传构建产物（可选）
    - uses: actions/upload-artifact@v4
      with:
        name: mingw-qt-build
        path: build/
