name: Qt6 Test CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Qt 6.6.3 with Multimedia and Tools
        uses: jurplel/install-qt-action@v2
        with:
          version: 6.6.3
          modules: 'qtbase qtmultimedia qttools'
          cache: true
          target: 'desktop'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build

      - name: Configure CMake project
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${Qt6_DIR}"

      - name: Build entire project
        run: |
          cd build
          cmake --build .

      - name: Run unit tests (HealthModelTest)
        run: |
          cd build
          ctest --output-on-failure
