name: Qt6 Windows CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.4.0'
        arch: 'x64'
        modules: 'qtcharts qtdeclarative qtgraphicaleffects qtimageformats qtmultimedia qtquickcontrols qtquickcontrols2 qtsvg qttools qttranslations qtwebengine qtwebview'
        
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.19'
        
    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        
    - name: Build project
      run: |
        cmake --build build --config Release --parallel
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Deploy application
      if: github.ref == 'refs/heads/main'
      run: |
        cd build
        cmake --install . --prefix ./install
        
    - name: Upload build artifacts
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: qt-app-windows
        path: build/install/
        retention-days: 30
