name: Qt Test CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.4.3'
        arch: 'x64'
        modules: 'qtbase qtmultimedia qttest'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Create build directory
      run: mkdir build
      
    - name: Configure CMake
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        echo "CMake configuration completed"
        
    - name: Build project
      run: |
        cd build
        make -j$(nproc)
        echo "Build completed"
        ls -la
        echo "Test directory contents:"
        ls -la test/ || echo "No test directory found"
        
    - name: Find test executable
      run: |
        cd build
        echo "Looking for test executables..."
        find . -name "*test*" -type f -executable
        find . -name "*Test*" -type f -executable
        
    - name: Run tests
      run: |
        cd build
        echo "Running tests..."
        if [ -f "./test/HealthModelTest" ]; then
          echo "Found HealthModelTest, running..."
          ./test/HealthModelTest
        elif [ -f "./HealthModelTest" ]; then
          echo "Found HealthModelTest in build root, running..."
          ./HealthModelTest
        else
          echo "Test executable not found!"
          exit 1
        fi
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          build/test/*.xml
          build/test/*.log
          build/*.xml
          build/*.log 